version: "3.7"
services:
    frontend:
      container_name: frontend
      image: mrizkiprmn/frontend-jenkins:master
      ports: 
          - "8687:80"
      networks: 
          - netnet
      environment:
          - VUE_APP_USERS=http://3.83.153.65:8282/api/

networks: 
    netnet:
        driver: bridge