version: "3.7"
services:
    frontend:
      container_name: frontend
      image: mrizkiprmn/frontend-jenkins:master
      ports: 
          - "8181:8080"
      networks: 
          - netnet
       env_file: 
          - ./frontend/.env.local


networks: 
    netnet:
        driver: bridge