- hosts: localhost
  connection: local
    
    
  vars: 
    registry : ghcr.io/mrizkiprmn
    proj     : app-frontend
    tag      : 0.1.0
    dir      : /home/mrizkiprmn/github
    
  pre_tasks:
  
    - name: install pre-requisites
      pip:
        name: 
        - docker

  tasks:

    - name: build image
      community.docker.docker_image:
        name: "{{registry}}/{{proj}}:{{tag}}"
        build:
          path: "{{dir}}/{{proj}}"
        source: build


    - name: push image to registry
      community.docker.docker_image:
        name: "{{registry}}/{{proj}}:{{tag}}"
        repository: "{{registry}}/{{proj}}:{{tag}}"
        push: yes
        source: local


    - name: remove image unused
      community.docker.docker_image:
        state: absent
        name: "{{registry}}/{{proj}}"
        tag: "{{tag}}"
        force_tag: yes