- hosts: localhost
  connection: local
    
    
  vars: 
    hub: "mrizkiprmn"
    proj: "app-frontend"
    tag: "windows"
    dir: /home/mrizkiprmn/github
    repo: https://github.com/mrizkiprmn/app-frontend.git

    
  pre_tasks:
  
    - name: install pre-requisites
      pip:
        name: 
        - docker

  tasks:

    - name: build image
      community.docker.docker_image:
        name: "{{hub}}/{{proj}}:{{tag}}"
        build:
          path: "{{dir}}/{{proj}}"
        source: build


    - name: push image to registry
      community.docker.docker_image:
        name: "{{hub}}/{{proj}}:{{tag}}"
        repository: "{{hub}}/{{proj}}:{{tag}}"
        push: yes
        source: local


    - name: remove image unused
      community.docker.docker_image:
        state: absent
        name: "{{hub}}/{{proj}}"
        tag: "{{tag}}"
        force_tag: yes