- hosts: localhost
  connection: local

  vars:
    project: fe
    namespace: app-frontend
    src: /home/mrizkiprmn/Documents/github/app-frontend/Charts/frontend

  pre_tasks:

    - name: install pre-requisites
      pip:
        name:
          - openshift
          - pyyaml
          - kubernetes 

    - name: install Helm Diff
      kubernetes.core.helm_plugin:
        state: present
        plugin_path: https://github.com/databus23/helm-diff
  
  tasks:

    - name: helm deploy
      kubernetes.core.helm:
        name: fe
        namespace: "{{ namespace }}"
        chart_ref: "{{ src }}"
