apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: app-frontend
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogImJYSnBlbXRwY0hKdGJqcE5hWEpoYUdSbGJHbHRZVEE0IgoJCX0KCX0KfQ==
type: kubernetes.io/dockerconfigjson
