name: Docker Build & Push

on: [push, pull_request]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@1.0.0
  
  publish_docker_image:
    needs: build
    runs-on: ubuntu-latest

    if: GitHub.ref == 'refs/heads/master' || GitHub.event_name == '0.1.0'
    steps:
    - name: Checkout
      uses: actions/checkout@1.0.0
    - name: Docker Meta
      id: meta
      uses: crazy-max/ghaction-docker-meta@v2
      with:
        images: mrizkiprmn/app-frontend
        tags: |
          type=raw,value=latest,enable=${{ endsWith(GitHub.ref, 'master') }}
          type=ref,event=tag
        flavor: |
          latest=false

    - name: Login to DockerHub
      if: GitHub.event_name != 'pull_request'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
  
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: ${{ GitHub.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}