name: Docker Build & Push

on: [push, pull_request]


jobs:
  Chekcout Code:
    needs: build
    runs-on: ubuntu-latest

    if: GitHub.ref == 'refs/heads/master' || GitHub.event_name == '0.1.0'
    steps:
    - name: Checkout
      uses: actions/checkout@1.0.0
    


  Login to Docker:
    - name: Login to Docker Registry
      if: GitHub.event_name != 'pull_request'
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
  

  Build and Push Images:
    - name: Build and push
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        registry: ghcr.io
        image: mrizkiprmn/app-frontend
        tags: 0.1.0
        
        